#ifndef DEFS_H
#define DEFS_H

#define TAG_DRONE_STATUS "DRONESTATUS"
#define TAG_PAYLOAD "PAYLOAD"
#define ATTR_VIDEO_URL "VIDEOURL"

#define TAG_POSITION "POSITION"
#define ATTR_NODE_TYPE "NODETYPE"
#define ATTR_DRONE_UID "DRONEUID"
#define ATTR_LONGITUDE "LONGITUDE"
#define ATTR_LATITUDE "LATITUDE"
#define ATTR_ALTITUDE "ALTITUDE"
#define ATTR_HEADING "HEADING"
#define ATTR_FLIGHT_STATUS "FLIGHTSTATUS"

#define TAG_BATTERY "BATTERY"
#define TAG_RETURN "RETURN"
#define ATTR_LEVEL "LEVEL"

#define TAG_MISSION_PLAN "MISSIONPLAN"
#define TAG_WAY_POINT "WAYPOINT"
#define TAG_WAY_POINT_METADATA "WAYPOINTMETADATA"
#define ATTR_WAY_POINT_TYPE "TYPE"
#define ATTR_WAY_POINT_SPEED "SPEED"
#define ATTR_WAY_POINT_CLOCKWISE "CLOCKWISE"

#define TAG_SAFETY_PLAN "SAFETYPLAN"

#define TAG_LANDING_PLAN "LANDINGPLAN"

#define TAG_DRONE_ERROR "DRONEERROR"
#define ATTR_ERROR "ERROR"

#define TAG_RECTANGLE "RECTANGLE"

#define TAG_EXCLUSION_AREA "EXCLUSIONAREA"
#define TAG_SHAPES "SHAPES"
#define TAG_SHAPE "SHAPE"
#define TAG_CIRCLE "CIRCLE"
#define ATTR_RADIUS "RADIUS"
#define ATTR_CENTER "CENTER"
#define TAG_TRIANGLE "TRIANGLE"
#define TAG_COORD "COORD"

#define TAG_TAKE_OFF "TAKEOFF"
#define TAG_FAIL_SAFE "FAILSAFE"
#define TAG_FAIL_SAFE_DONE "FAILSAFEDONE"

#endif // DEFS_H
